sudo: required
services:
  - docker

before_install:
  - docker build -t karnan/docker-react -f Dockerfile.dev .

script:
  - docker run karnan/docker-react npm run test -- --coverage
deploy:
  provider: elasticebeanstalk
  region: "us-east-2"
  app: "docker-project"
  env: "DockerProject-env"
  bucket_name: "elasticbeanstalk-us-east-2-328368778269"
  bucket_path: "docker-project"
  on:
    branches:
      only:
        - master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "AWS_SECRET_KEY"
